name: Tarkov
services:
  nginx:
    image: nginx:stable-alpine
    container_name: tarkov-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/tarkov
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - tarkov
  mysql:
    container_name: tarkov-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1237890qwe
      MYSQL_DATABASE: tarkov
      MYSQL_USER: tarkov
      MYSQL_PASSWORD: tarkov
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tarkov
  php:
    container_name: tarkov-php
    user: "1000:1000"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: 'serverName=tarkov'
    volumes:
      - .:/var/www/tarkov
    networks:
      - tarkov
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
volumes:
  mysql_data:
networks:
  tarkov:
    driver: bridge
    name: tarkov
