name: Deploy tarkov-back

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to server
              run: |
                  ssh -o StrictHostKeyChecking=no root@a.tarkov-anubis.ru << 'EOF'
                    cd /var/www/tarkov-back
                    git pull origin master
                    composer install --no-interaction --prefer-dist --optimize-autoloader
                    php bin/console doctrine:migrations:migrate --no-interaction
                    php bin/console cache:clear
                    php bin/console cache:warmup
                    pm2 restart tarkov-back || pm2 start php -f --name=tarkov-back -- -S 127.0.0.1:8000 -t public
                  EOF